// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.4
// Project name: jingcai_3_2_dark

#include "ui.h"

void ui_Screen5_screen_init(void)
{
ui_Screen5 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel14 = lv_obj_create(ui_Screen5);
lv_obj_set_width( ui_Panel14, 823);
lv_obj_set_height( ui_Panel14, 47);
lv_obj_set_x( ui_Panel14, -7 );
lv_obj_set_y( ui_Panel14, -217 );
lv_obj_set_align( ui_Panel14, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label31 = lv_label_create(ui_Panel14);
lv_obj_set_width( ui_Label31, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label31, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label31, 3 );
lv_obj_set_y( ui_Label31, 2 );
lv_obj_set_align( ui_Label31, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label31,"Settings");
lv_obj_set_style_text_font(ui_Label31, &ui_font_Font1YHall16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button16 = lv_btn_create(ui_Panel14);
lv_obj_set_width( ui_Button16, 46);
lv_obj_set_height( ui_Button16, 30);
lv_obj_set_x( ui_Button16, -201 );
lv_obj_set_y( ui_Button16, 1 );
lv_obj_set_align( ui_Button16, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_Button16, &ui_font_Font1YHall16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label36 = lv_label_create(ui_Button16);
lv_obj_set_width( ui_Label36, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label36, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label36, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label36,"Back");

ui_Panel17 = lv_obj_create(ui_Screen5);
lv_obj_set_width( ui_Panel17, 765);
lv_obj_set_height( ui_Panel17, 72);
lv_obj_set_x( ui_Panel17, 2 );
lv_obj_set_y( ui_Panel17, -137 );
lv_obj_set_align( ui_Panel17, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Panel17, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Panel17, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label15 = lv_label_create(ui_Panel17);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, -126 );
lv_obj_set_y( ui_Label15, -11 );
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"Music player network album picture display function");
lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label16 = lv_label_create(ui_Panel17);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, -141 );
lv_obj_set_y( ui_Label16, 14 );
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16," (experimental function, may cause restart, memory overflow)");

ui_Switch2 = lv_switch_create(ui_Panel17);
lv_obj_set_width( ui_Switch2, 74);
lv_obj_set_height( ui_Switch2, 38);
lv_obj_set_x( ui_Switch2, 317 );
lv_obj_set_y( ui_Switch2, 1 );
lv_obj_set_align( ui_Switch2, LV_ALIGN_CENTER );


ui_Label37 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label37, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label37, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label37, 0 );
lv_obj_set_y( ui_Label37, 217 );
lv_obj_set_align( ui_Label37, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label37,"GUITION V2.0.5");

ui_Panel6 = lv_obj_create(ui_Screen5);
lv_obj_set_width( ui_Panel6, 455);
lv_obj_set_height( ui_Panel6, 119);
lv_obj_set_x( ui_Panel6, -1 );
lv_obj_set_y( ui_Panel6, -112 );
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label13 = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, -110 );
lv_obj_set_y( ui_Label13, -26 );
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"Set screen brightness");
lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Slider1 = lv_slider_create(ui_Panel6);
lv_slider_set_value( ui_Slider1, 100, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider1, 401);
lv_obj_set_height( ui_Slider1, 19);
lv_obj_set_x( ui_Slider1, -6 );
lv_obj_set_y( ui_Slider1, 20 );
lv_obj_set_align( ui_Slider1, LV_ALIGN_CENTER );


lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);

}
